#ifndef EXTI_PRIVATE_H_
#define EXTI_PRIVATE_H_


#define  APB_GPIO_PORTA_BASE_ADDRESS			 0x40004000
#define  APB_GPIO_PORTB_BASE_ADDRESS			 0x40005000
#define  APB_GPIO_PORTC_BASE_ADDRESS			 0x40006000
#define  APB_GPIO_PORTD_BASE_ADDRESS			 0x40007000
#define  APB_GPIO_PORTE_BASE_ADDRESS			 0x40024000
#define  APB_GPIO_PORTF_BASE_ADDRESS 		     0x40025000  



#define  APB_GPIO_PORTA_OFFSET			 0x00004000
#define  APB_GPIO_PORTB_OFFSET			 0x00005000
#define  APB_GPIO_PORTC_OFFSET			 0x00006000
#define  APB_GPIO_PORTD_OFFSET			 0x00007000
#define  APB_GPIO_PORTE_OFFSET			 0x00024000
#define  APB_GPIO_PORTF_OFFSET 		     0x00025000  

#define	GPIOIS_OFFSET					0x404
#define	GPIOIBE_OFFSET					0x408
#define	GPIOIEV_OFFSET					0x40C
#define	GPIOIM_OFFSET					0x410
#define	GPIORIS_OFFSET					0x414  
#define	GPIOMIS_OFFSET					0x418
#define	GPIOICR_OFFSET					0x41C



#define APB_GPIOA_IS						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOA_IBE						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOA_IEV						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOA_IM						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOA_RIS						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOA_MIS						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOA_ICR						*((volatile uint32*)(APB_GPIO_PORTA_BASE_ADDRESS+GPIOICR_OFFSET))


#define APB_GPIOB_IS						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOB_IBE						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOB_IEV						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOB_IM						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOB_RIS						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOB_MIS						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOB_ICR						*((volatile uint32*)(APB_GPIO_PORTB_BASE_ADDRESS+GPIOICR_OFFSET))


#define APB_GPIOC_IS						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOC_IBE						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOC_IEV						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOC_IM						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOC_RIS						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOC_MIS						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOC_ICR						*((volatile uint32*)(APB_GPIO_PORTC_BASE_ADDRESS+GPIOICR_OFFSET))


#define APB_GPIOD_IS						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOD_IBE						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOD_IEV						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOD_IM						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOD_RIS						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOD_MIS						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOD_ICR						*((volatile uint32*)(APB_GPIO_PORTD_BASE_ADDRESS+GPIOICR_OFFSET))


#define APB_GPIOE_IS						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOE_IBE						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOE_IEV						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOE_IM						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOE_RIS						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOE_MIS						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOE_ICR						*((volatile uint32*)(APB_GPIO_PORTE_BASE_ADDRESS+GPIOICR_OFFSET))



#define APB_GPIOF_IS						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOIS_OFFSET))
#define APB_GPIOF_IBE						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOIBE_OFFSET))
#define APB_GPIOF_IEV						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOIEV_OFFSET))
#define APB_GPIOF_IM						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOIM_OFFSET))
#define APB_GPIOF_RIS						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIORIS_OFFSET))
#define APB_GPIOF_MIS						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOMIS_OFFSET))
#define APB_GPIOF_ICR						*((volatile uint32*)(APB_GPIO_PORTF_BASE_ADDRESS+GPIOICR_OFFSET))



#endif